import type { WeeklyProjectedPlayer, ProjectedStatLine } from '@/lib/fantasy/lineup-types';
import type { NflverseTeamWeek } from '@/lib/fantasy/nflverse-team-stats';
import type { ProjectionOverrideRecord } from '@/lib/fantasy/projection-overrides';
import type { PlayerProjectionCandidate, TeamOpportunityPlan } from '@/lib/fantasy/projection-opportunity-types';
import { buildUsageProfile, carryPrior, clamp, finite, participationFactor, passPrior, receivingTouchdownPrior, rushTouchdownPrior, targetPrior } from '@/lib/fantasy/projection-usage';
import { projectTeamOpportunityPlan } from '@/lib/fantasy/projection-team-plan';
import { allocatePool, expectedTouchdownPools, mergeAllocations, mergeAssumption, rate, refreshBonuses, roleLabel, score, soften } from '@/lib/fantasy/projection-allocation-helpers';

export function reconcileTeamOpportunityBudgets(args:{candidates:PlayerProjectionCandidate[];currentRowsByTeam:Map<string,NflverseTeamWeek[]>;previousRowsByTeam:Map<string,NflverseTeamWeek[]>;preseason:boolean;scoring:Record<string,number>;teamOverrides:Map<string,ProjectionOverrideRecord>}):{players:WeeklyProjectedPlayer[];plans:Record<string,TeamOpportunityPlan>}{
 const byTeam=new Map<string,PlayerProjectionCandidate[]>();const passthrough:WeeklyProjectedPlayer[]=[];for(const c of args.candidates){const team=c.base.nflTeam;if(!team||c.base.isBye){passthrough.push(c.base);continue;}const list=byTeam.get(team)||[];list.push(c);byTeam.set(team,list);}const players=[...passthrough];const plans:Record<string,TeamOpportunityPlan>={};
 for(const[team,candidates]of byTeam){const plan=projectTeamOpportunityPlan({team,currentRows:args.currentRowsByTeam.get(team)||[],previousRows:args.previousRowsByTeam.get(team)||[],candidates,preseason:args.preseason,teamOverride:args.teamOverrides.get(team)});plans[team]=plan;
  const passes=allocatePool({candidates,pool:plan.passAttempts,eligible:c=>c.base.position==='QB',rawWeight:passPrior,overrideShare:o=>o?.passAttemptShare??null});
  const targets=allocatePool({candidates,pool:plan.targetPool,eligible:c=>['RB','WR','TE'].includes(c.base.position),rawWeight:targetPrior,overrideShare:o=>o?.targetShare??null});
  const nonRbCandidates=candidates.filter(c=>c.base.position==='QB'||c.base.position==='WR');
  const nonRbPrior=nonRbCandidates.reduce((sum,c)=>sum+carryPrior(c,buildUsageProfile(c)),0);
  const hasRbs=candidates.some(c=>c.base.position==='RB');const hasNonRbs=nonRbCandidates.length>0;
  const nonRbPool=!hasNonRbs?0:!hasRbs?plan.rushAttempts:clamp(nonRbPrior,0,plan.rushAttempts*.34);
  const rbPool=Math.max(0,plan.rushAttempts-nonRbPool);
  const nonRbCarries=allocatePool({candidates,pool:nonRbPool,shareDenominator:plan.rushAttempts,eligible:c=>c.base.position==='QB'||c.base.position==='WR',rawWeight:carryPrior,overrideShare:o=>o?.carryShare??null});
  const rbCarries=allocatePool({candidates,pool:rbPool,shareDenominator:plan.rushAttempts,eligible:c=>c.base.position==='RB',rawWeight:carryPrior,overrideShare:o=>o?.carryShare??null});
  const carries=mergeAllocations(nonRbCarries,rbCarries);
  const touchdownPools=expectedTouchdownPools(plan);
  const passTds=allocatePool({candidates,pool:touchdownPools.passing,eligible:c=>c.base.position==='QB',rawWeight:passPrior});
  const receivingTds=allocatePool({candidates,pool:touchdownPools.passing,eligible:c=>['RB','WR','TE'].includes(c.base.position),rawWeight:receivingTouchdownPrior});
  const rushingTds=allocatePool({candidates,pool:touchdownPools.rushing,eligible:c=>['QB','RB','WR'].includes(c.base.position),rawWeight:rushTouchdownPrior});
  for(const c of candidates){const position=c.base.position;if(!['QB','RB','WR','TE'].includes(position)){players.push({...c.base,teamPassAttempts:Number(plan.passAttempts.toFixed(1)),teamRushAttempts:Number(plan.rushAttempts.toFixed(1)),allocationSource:plan.source,workloadUncertainty:plan.uncertaintyMultiplier,overrideApplied:Boolean(c.override)});continue;}
   const original=c.base.statLine||{};const line:ProjectedStatLine={...original};const pass=passes.get(c.id),target=targets.get(c.id),carry=carries.get(c.id);const targetShare=target?.share||0,carryShare=carry?.share||0,passShare=pass?.share||0;const profile=pass?.profile||target?.profile||carry?.profile||buildUsageProfile(c);const active=clamp(c.override?.activeProbability??c.base.activeProbability,0,1);const start=clamp(c.override?.startProbability??c.base.startProbability,0,1);
   if(position==='QB'){const a=pass?.amount||0;const cr=clamp(rate(original,'pass_cmp','pass_att',.635),.48,.76);const ypa=clamp(rate(original,'pass_yd','pass_att',6.8)*soften(plan.passingEfficiencyFactor),5.1,9.3);const ir=clamp(rate(original,'pass_int','pass_att',.023)/Math.max(.97,soften(plan.passingEfficiencyFactor)),.008,.05);line.pass_att=a;line.pass_cmp=a*cr;line.pass_inc=Math.max(0,a-line.pass_cmp);line.pass_yd=a*ypa;line.pass_td=passTds.get(c.id)?.amount||0;line.pass_int=a*ir;line.pass_fd=line.pass_cmp*.49;line.pass_2pt=.04*active*start;}
   if(['QB','RB','WR'].includes(position)){const a=carry?.amount||0;const fy=position==='QB'?4.7:position==='RB'?4.15:6;const ypa=clamp(rate(original,'rush_yd','rush_att',fy)*soften(plan.rushingEfficiencyFactor),position==='WR'?2.5:2.2,position==='WR'?11:8.5);line.rush_att=a;line.rush_yd=a*ypa;line.rush_td=rushingTds.get(c.id)?.amount||0;line.rush_fd=a*(position==='QB'?.22:.2);}
   if(['RB','WR','TE'].includes(position)){const n=target?.amount||0;const fc=position==='RB'?.73:position==='TE'?.68:.63;const fy=position==='RB'?6.2:position==='TE'?7:8;const cr=clamp(rate(original,'rec','rec_tgt',fc),.42,.88);const ypt=clamp(rate(original,'rec_yd','rec_tgt',fy)*soften(plan.passingEfficiencyFactor),4,12.5);line.rec_tgt=n;line.rec=n*cr;line.rec_yd=n*ypt;line.rec_td=receivingTds.get(c.id)?.amount||0;line.rec_fd=line.rec*(position==='TE'?.48:position==='RB'?.38:.44);}
   refreshBonuses(line,position);const rawReconciled=Math.max(0,score(line,args.scoring,position));const reconciled=rawReconciled*active;const individual=Math.max(0,c.base.projection);const fantasy=c.fantasyBaseline;const fantasyWeight=(fantasy?.anchorWeight||0)*active;const teamWeight=position==='QB'?.72:.66;const individualWeight=1-teamWeight;const model=(reconciled*teamWeight)+(individual*individualWeight);const fantasyExpected=(fantasy?.weightedPoints||0)*active;const computed=fantasy?model*(1-fantasyWeight)+fantasyExpected*fantasyWeight:model;const projection=Number.isFinite(c.override?.projectionPoints)?Math.max(0,Number(c.override?.projectionPoints)):computed;
   const label=position==='QB'?`${finite(line.pass_att).toFixed(0)} pass attempts, ${finite(line.rush_att).toFixed(1)} rushes`:position==='RB'?`${finite(line.rush_att).toFixed(1)} carries, ${finite(line.rec_tgt).toFixed(1)} targets`:`${finite(line.rec_tgt).toFixed(1)} targets${finite(line.rush_att)>=.5?`, ${finite(line.rush_att).toFixed(1)} rushes`:''}`;
   const context=profile.changedTeams?'Previous-team production remains a meaningful fantasy baseline while current-team opportunity is reconciled separately.':profile.roleTrend==='expanded'?'Recent games show a sustained workload expansion that is weighted above earlier-season usage.':profile.roleTrend==='declining'?'Recent games show a sustained workload decline that is weighted below earlier-season usage.':profile.rookie&&profile.sampleGames===0?'NFL workload uses a rookie prior informed by draft capital and current role.':null;const override=c.override?(c.override.note?`Manual projection override: ${c.override.note}`:'A temporary manual projection override is active.'):null;
   const trendUncertainty=profile.roleTrend==='expanded'||profile.roleTrend==='declining'?1.1:1;const dataQuality=c.base.dataQuality||'normal';
   players.push({...c.base,projection:Number(projection.toFixed(1)),baseline:Number(computed.toFixed(1)),statLine:Object.fromEntries(Object.entries(line).map(([k,v])=>[k,Number(v.toFixed(3))])),expectedRole:roleLabel(c,targetShare,carryShare,passShare,profile),workload:label,assumption:mergeAssumption(c.base.assumption,context,override),startProbability:start,activeProbability:active,availabilityWeight:active,workloadProbability:Number(profile.workloadProbability.toFixed(3)),roleTrend:profile.roleTrend,dataQuality,targetShare:target?Number(targetShare.toFixed(3)):undefined,carryShare:carry?Number(carryShare.toFixed(3)):undefined,teamPassAttempts:Number(plan.passAttempts.toFixed(1)),teamRushAttempts:Number(plan.rushAttempts.toFixed(1)),allocationSource:c.override?.projectionPoints!=null?'manual':plan.source,overrideApplied:Boolean(c.override),workloadUncertainty:Number((plan.uncertaintyMultiplier*(profile.changedTeams?1.06:profile.rookie&&profile.sampleGames===0?1.18:1)*trendUncertainty*(dataQuality==='degraded'?1.12:1)).toFixed(3)),projectionTrace:{individualModelPoints:Number(individual.toFixed(2)),reconciledStatLinePoints:Number(reconciled.toFixed(2)),fantasyBaselinePoints:fantasy?Number(fantasy.weightedPoints.toFixed(2)):null,fantasyBaselineWeight:Number(fantasyWeight.toFixed(3)),teamOpportunityWeight:teamWeight,activeProbability:active,workloadProbability:Number(profile.workloadProbability.toFixed(3)),roleTrend:profile.roleTrend,roleTrendFactor:Number(profile.roleTrendFactor.toFixed(3)),rosterRelevance:Number(profile.rosterRelevance.toFixed(3)),dataQuality,adjustments:[profile.changedTeams?'team-change-continuity':'same-team-continuity',fantasy?.established?'established-fantasy-baseline':'limited-or-no-fantasy-baseline',`role-trend-${profile.roleTrend}`,`participation-${participationFactor(c,profile).toFixed(3)}`,`roster-relevance-${profile.rosterRelevance.toFixed(3)}`]}});
  }
 }
 return{players,plans};
}
