/**
 * Newsletter Publish Endpoint
 *
 * The ONLY place a newsletter becomes publicly visible. Autogenerated newsletters
 * are saved as drafts (status:'draft'); this endpoint flips an existing draft to
 * 'published' (the explicit admin action) and, by default, announces it to Discord.
 *
 * Body: { season, week, sendDiscord?: boolean (default true), resendDiscord?: boolean, html? }
 *  - sendDiscord:false        → publish WITHOUT posting Discord
 *  - resendDiscord:true       → bypass the dedupe and re-post (explicit resend)
 *  - html                     → optional override of stored HTML (e.g. last-minute edit)
 *
 * Idempotent: re-publishing only refreshes metadata; the Discord dedupe (keyed by
 * season-week) guarantees the webhook is never sent twice for the same publish.
 */

import { NextRequest, NextResponse } from 'next/server';
import { cookies } from 'next/headers';
import { isAdminCookieValue } from '@/lib/auth/admin';
import { publishNewsletter, markNewsletterDiscordPosted } from '@/server/db/newsletter-queries';
import { postToDiscordWebhook, buildNewsletterEmbed } from '@/lib/utils/discord';
import { updateBotMemoryFromPublish } from '@/lib/newsletter/publish-memory';
import { getDb } from '@/server/db/client';
import { discordNotifications } from '@/server/db/schema';
import { eq, and } from 'drizzle-orm';

export const runtime = 'nodejs';
export const dynamic = 'force-dynamic';

export async function POST(req: NextRequest) {
  // Admin auth check
  const cookieStore = await cookies();
  const adminCookie = cookieStore.get('evw_admin')?.value;
  if (!isAdminCookieValue(adminCookie)) {
    return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
  }

  let body: { season: number; week: number; sendDiscord?: boolean; resendDiscord?: boolean; html?: string };
  try {
    body = await req.json();
  } catch {
    return NextResponse.json({ error: 'Invalid JSON body' }, { status: 400 });
  }

  const { season, week, html } = body;
  // Discord defaults ON (opt-out): the primary Publish action announces; callers
  // pass sendDiscord:false for "Publish without Discord".
  const sendDiscord = body.sendDiscord !== false;
  const resendDiscord = body.resendDiscord === true;

  if (season === undefined || week === undefined) {
    return NextResponse.json({ error: 'Missing required fields: season, week' }, { status: 400 });
  }

  const seasonNum = Number(season);
  const weekNum = Number(week);

  try {
    // ── Flip the existing draft → published. Never overwrites content/sections. ──
    const { found, alreadyPublished } = await publishNewsletter(seasonNum, weekNum, { html });
    if (!found) {
      return NextResponse.json({
        error: `No newsletter found for Season ${seasonNum} Week ${weekNum}. Generate it first.`,
      }, { status: 404 });
    }

    console.log(`[Publish] Season ${seasonNum} Week ${weekNum} published${alreadyPublished ? ' (was already published)' : ''}. sendDiscord=${sendDiscord}`);

    // ── Discord announcement — single authoritative place, only on explicit opt-in ──
    let discordPosted = false;
    let discordSkippedReason: string | null = null;
    if (!sendDiscord) {
      discordSkippedReason = 'sendDiscord=false';
    } else {
      const discordWebhookUrl = process.env.DISCORD_NEWSLETTER_WEBHOOK_URL;
      const siteUrl = process.env.SITE_URL || 'https://eastvswest.football';
      if (!discordWebhookUrl) {
        discordSkippedReason = 'DISCORD_NEWSLETTER_WEBHOOK_URL not configured';
      } else {
        try {
          const db = getDb();
          const dedupeKey = `${seasonNum}-${weekNum}`;
          const existing = resendDiscord
            ? []
            : await db.select().from(discordNotifications)
                .where(and(eq(discordNotifications.notificationType, 'newsletter_published'), eq(discordNotifications.dedupeKey, dedupeKey)))
                .limit(1).catch(() => []);
          if (existing.length === 0) {
            console.log(`[Publish] Posting Discord embed for Season ${seasonNum} Week ${weekNum}${resendDiscord ? ' (explicit resend)' : ''}`);
            const embed = buildNewsletterEmbed({ season: seasonNum, week: weekNum, siteUrl });
            const discordRes = await postToDiscordWebhook(discordWebhookUrl, { embeds: [embed] });
            if (discordRes.success) {
              // Record dedupe + mark on the newsletter row (best-effort).
              if (!resendDiscord) {
                await db.insert(discordNotifications).values({ notificationType: 'newsletter_published', dedupeKey, meta: { season: seasonNum, week: weekNum } }).catch(() => {});
              }
              await markNewsletterDiscordPosted(seasonNum, weekNum);
              discordPosted = true;
              console.log(`[Publish] Discord embed posted — Season ${seasonNum} Week ${weekNum}`);
            } else {
              discordSkippedReason = `Discord post failed: ${discordRes.error}`;
              console.warn(`[Publish] ${discordSkippedReason}`);
            }
          } else {
            discordSkippedReason = 'already posted (dedupe)';
            console.log(`[Publish] Discord already posted for Season ${seasonNum} Week ${weekNum} — skipping`);
          }
        } catch (discordErr) {
          discordSkippedReason = 'Discord notification error (non-fatal)';
          console.warn('[Publish] Discord notification error (non-fatal):', discordErr);
        }
      }
    }

    // Append editorial corrections to bot memory (non-fatal — runs after Discord webhook)
    await updateBotMemoryFromPublish(seasonNum, weekNum);

    return NextResponse.json({
      success: true,
      alreadyPublished,
      discordPosted,
      discordSkippedReason,
      message: `Season ${seasonNum} Week ${weekNum} published successfully${discordPosted ? ' and announced to Discord' : sendDiscord ? ` (Discord not sent: ${discordSkippedReason})` : ' (Discord skipped)'}.`,
    });
  } catch (err) {
    const message = err instanceof Error ? err.message : String(err);
    console.error('[Publish] Failed to publish newsletter:', message);
    return NextResponse.json({ error: `Failed to publish: ${message}` }, { status: 500 });
  }
}
