-- Newsletter draft/publish status + editorial calendar queue.
--
-- Before this change, any row in `newsletters` was publicly visible and every
-- generation path wrote here directly (= autopublish). We add a publish gate so
-- autogenerated newsletters are saved as 'draft' and only become public via an
-- explicit admin publish action.

-- 1. Add publish-gate columns to newsletters.
ALTER TABLE newsletters ADD COLUMN IF NOT EXISTS status        varchar(16);
ALTER TABLE newsletters ADD COLUMN IF NOT EXISTS published_at  timestamptz;
ALTER TABLE newsletters ADD COLUMN IF NOT EXISTS updated_at    timestamptz;
ALTER TABLE newsletters ADD COLUMN IF NOT EXISTS episode_type  varchar(64);

-- Backfill existing rows: they were already public, so mark them published and
-- seed published_at/updated_at from generated_at to keep them visible.
UPDATE newsletters SET status = 'published' WHERE status IS NULL;
UPDATE newsletters SET published_at = generated_at WHERE published_at IS NULL;
UPDATE newsletters SET updated_at = generated_at WHERE updated_at IS NULL;

-- Lock down defaults / not-null now that rows are backfilled.
ALTER TABLE newsletters ALTER COLUMN status SET DEFAULT 'published';
ALTER TABLE newsletters ALTER COLUMN status SET NOT NULL;
ALTER TABLE newsletters ALTER COLUMN updated_at SET DEFAULT now();
ALTER TABLE newsletters ALTER COLUMN updated_at SET NOT NULL;

CREATE INDEX IF NOT EXISTS newsletters_status_idx ON newsletters (status);

-- 2. Editorial calendar / generation queue.
DO $$ BEGIN
  CREATE TYPE newsletter_queue_status AS ENUM
    ('queued', 'generated', 'skipped', 'failed', 'published', 'archived');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

CREATE TABLE IF NOT EXISTS newsletter_queue (
  id            uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  season        integer NOT NULL,
  week          integer,
  episode_type  varchar(64) NOT NULL,
  scheduled_for timestamptz NOT NULL,
  status        newsletter_queue_status NOT NULL DEFAULT 'queued',
  note          text,
  generated_at  timestamptz,
  error         text,
  created_at    timestamptz NOT NULL DEFAULT now(),
  updated_at    timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS newsletter_queue_status_scheduled_idx
  ON newsletter_queue (status, scheduled_for);
