import { TEAM_CARD_OUTPUT_SCHEMA, TEAM_CARD_TOOL_META } from '@/lib/mcp/widgets/team-card';
import { TRADE_ANALYZER_OUTPUT_SCHEMA, TRADE_ANALYZER_TOOL_META } from '@/lib/mcp/widgets/trade-analyzer';
import { TEAM_COMPARE_OUTPUT_SCHEMA, TEAM_COMPARE_TOOL_META } from '@/lib/mcp/widgets/team-compare';
import { TRADE_BLOCK_OUTPUT_SCHEMA, TRADE_BLOCK_TOOL_META } from '@/lib/mcp/widgets/trade-block';
import { DRAFT_BOARD_OUTPUT_SCHEMA, DRAFT_BOARD_TOOL_META } from '@/lib/mcp/widgets/draft-board';
import { PICK_BOARD_OUTPUT_SCHEMA, PICK_BOARD_TOOL_META } from '@/lib/mcp/widgets/pick-board';
import { FRANCHISE_CASE_OUTPUT_SCHEMA, FRANCHISE_CASE_TOOL_META } from '@/lib/mcp/widgets/franchise-case';
import { ROSTER_STRENGTH_OUTPUT_SCHEMA, ROSTER_STRENGTH_TOOL_META } from '@/lib/mcp/widgets/roster-strength';

type Property = Record<string, unknown>;
const objectInput = (properties: Record<string, Property> = {}, required: string[] = []) => ({ type: 'object', properties, required });
const stringProp = (description: string) => ({ type: 'string', description });
const numberProp = (description: string) => ({ type: 'number', description });
const booleanProp = (description: string) => ({ type: 'boolean', description });
const enumProp = (description: string, values: string[]) => ({ type: 'string', description, enum: values });
const tool = (name: string, description: string, inputSchema = objectInput()) => ({ name, description, inputSchema });

const GAME_TYPE_VALUES = ['all', 'regular', 'playoffs', 'toilet', 'postseason'];
const PLAYER_POSITION_VALUES = ['QB', 'RB', 'WR', 'TE', 'K', 'DEF'];

export const MCP_TOOLS = [
  tool('get_league_info', 'Returns East v. West league rules, scoring, roster settings, payouts, dates, and champions.'),
  tool('get_current_standings', 'Returns live current-season standings and all-time franchise standings.'),
  tool('get_team_dashboard', 'Returns one team record, full roster, all-time stats, and championship history.', objectInput({ name: stringProp('Team name or alias.') }, ['name'])),
  { ...tool('show_team_card', 'Renders the visual East v. West Team Card for one team. Use when the user asks to show, display, open, or render a team card.', objectInput({ name: stringProp('Team name or alias.') }, ['name'])), _meta: TEAM_CARD_TOOL_META, outputSchema: TEAM_CARD_OUTPUT_SCHEMA },
  tool('get_current_roster', 'Returns current rosters for all teams or one team.', objectInput({ team: stringProp('Optional team filter.') })),
  tool('search_players', 'Searches the current Sleeper player directory by name. For historical EVW statistics and league-career filters, use search_evw_players.', objectInput({ name: stringProp('Player name.'), limit: numberProp('Maximum results, up to 20.') }, ['name'])),
  tool('get_player_info', 'Returns one current Sleeper player profile and fantasy owner. For the complete EVW career, honors, transactions, game log, and postseason splits, use get_evw_player.', objectInput({ id: stringProp('Sleeper player ID.') }, ['id'])),
  tool('get_current_matchups', 'Returns current fantasy matchups and scores.', objectInput({ week: numberProp('Optional NFL week.') })),
  tool('get_recent_transactions', 'Returns recent waiver and free-agent moves.', objectInput({ limit: numberProp('Maximum results.'), team: stringProp('Optional team filter.'), season: stringProp('Optional season.') })),
  tool('get_trade_history', 'Returns trade history with players and picks.', objectInput({ team: stringProp('Optional team filter.'), season: stringProp('Optional season.'), limit: numberProp('Maximum trades.') })),
  { ...tool('get_draft_history', 'Returns completed draft history and future-pick ownership. Renders a visual round-by-round draft board.', objectInput({ season: stringProp('Optional season.'), team: stringProp('Optional team filter.'), type: { type: 'string', enum: ['history', 'future'] } })), _meta: DRAFT_BOARD_TOOL_META, outputSchema: DRAFT_BOARD_OUTPUT_SCHEMA },
  tool('get_draft_picks', 'Returns future draft-pick ownership.', objectInput({ team: stringProp('Optional team filter.') })),
  { ...tool('get_franchise_summary', 'Returns all-time franchise records and championships. Renders a visual trophy-case ranking. For the full statistical franchise archive, use get_franchise_history.', objectInput({ team: stringProp('Optional team filter.') })), _meta: FRANCHISE_CASE_TOOL_META, outputSchema: FRANCHISE_CASE_OUTPUT_SCHEMA },
  tool('answer_rule_question', 'Searches or opens East v. West rulebook sections.', objectInput({ search: stringProp('Optional keyword.'), section: stringProp('Optional section ID.') })),
  tool('get_weekly_content_context', 'Returns the weekly league content briefing.'),
  tool('get_commissioner_ops_context', 'Returns the read-only commissioner operations briefing.'),
  tool('get_league_overview', 'Returns a complete all-team league snapshot.'),
  tool('get_position_rooms', 'Returns roster position groups.', objectInput({ team: stringProp('Optional team filter.'), position: stringProp('Optional position filter.') })),
  { ...tool('compare_teams', 'Compares exactly two teams. Renders a visual head-to-head comparison card.', objectInput({ team1: stringProp('First team.'), team2: stringProp('Second team.') }, ['team1', 'team2'])), _meta: TEAM_COMPARE_TOOL_META, outputSchema: TEAM_COMPARE_OUTPUT_SCHEMA },
  { ...tool('get_future_pick_board', 'Returns future draft picks organized by team. Renders a visual pick board.'), _meta: PICK_BOARD_TOOL_META, outputSchema: PICK_BOARD_OUTPUT_SCHEMA },
  { ...tool('get_trade_block', 'Returns the current trade block. Renders a visual trade-block board.', objectInput({ team: stringProp('Optional team filter.') })), _meta: TRADE_BLOCK_TOOL_META, outputSchema: TRADE_BLOCK_OUTPUT_SCHEMA },
  tool('get_power_rankings', 'Returns current power rankings.'),
  { ...tool('analyze_roster', 'Returns a roster-strength analysis for one team. Renders a visual position-strength breakdown.', objectInput({ name: stringProp('Team name or alias.') }, ['name'])), _meta: ROSTER_STRENGTH_TOOL_META, outputSchema: ROSTER_STRENGTH_OUTPUT_SCHEMA },
  { ...tool('analyze_trade', 'Analyzes two trade sides using available value sources. Renders a visual side-by-side trade grade.', objectInput({ side_a: { type: 'array', items: { type: 'string' } }, side_b: { type: 'array', items: { type: 'string' } }, source: { type: 'string', enum: ['avg', 'fc', 'ktc'] } }, ['side_a', 'side_b'])), _meta: TRADE_ANALYZER_TOOL_META, outputSchema: TRADE_ANALYZER_OUTPUT_SCHEMA },
  tool('get_player_values', 'Returns dynasty values for named players or picks.', objectInput({ players: { type: 'array', items: { type: 'string' } } }, ['players'])),

  tool('get_league_data_model', 'Returns the authoritative East v. West statistical semantics and coverage model. Use this when interpreting EVW points, franchise identity, Playoffs vs Toilet Bowl, All-EVW honors, or postseason categories.'),
  tool('get_evw_player', 'Returns the complete canonical East v. West player profile plus the research-backend ownership timeline. Accepts either Sleeper ID or an unambiguous player name.', objectInput({ id: stringProp('Optional Sleeper player ID.'), player: stringProp('Optional player name.'), name: stringProp('Optional player name alias.') })),
  tool('search_evw_players', 'Searches historical East v. West player careers with league-stat filters. EVW points are ownership-attributed.', objectInput({ query: stringProp('Optional partial player name.'), position: enumProp('Optional position.', PLAYER_POSITION_VALUES), franchise: stringProp('Optional current or historical franchise name/alias.'), season: stringProp('Optional season the player must have appeared in.'), min_points: numberProp('Minimum career EVW points.'), min_starts: numberProp('Minimum EVW starts.'), min_weeks: numberProp('Minimum rostered EVW weeks.'), award: enumProp('Optional honor filter.', ['all_evw_first', 'all_evw_second', 'mvp', 'rookie_of_year']), exclude_defenses: booleanProp('Exclude DEF/DST rows.'), limit: numberProp('Maximum results, 1-100.') })),
  tool('get_franchise_history', 'Returns one canonical franchise reference archive with regular-season history, separate Playoff/Toilet Bowl/other-postseason records, championships, season results, player leaders, records, All-EVW selections, milestones, and optionally historical games.', objectInput({ team: stringProp('Canonical franchise name, historical alias, or franchise history ID.'), include_games: booleanProp('Include historical game rows. Defaults false.'), limit: numberProp('Maximum milestone/game rows, 1-100.') }, ['team'])),
  tool('get_league_records', 'Returns ranked East v. West record lists plus the immutable completed-season record-book snapshot. Playoffs and Toilet Bowl remain separate.', objectInput({ category: enumProp('Record category.', ['all', 'player_career', 'player_season', 'player_game', 'team_game', 'franchise']), position: enumProp('Optional player position filter.', PLAYER_POSITION_VALUES), game_type: enumProp('Statistical game category.', GAME_TYPE_VALUES), exclude_defenses: booleanProp('Exclude DEF/DST from player lists.'), include_progression: booleanProp('Include chronological record progressions.'), limit: numberProp('Maximum ranked rows per category, 1-100.') })),
  tool('get_season_archive', 'Returns a complete East v. West season reference snapshot: standings, player leaders, championship result, All-EVW teams, MVP/ROY, weekly highs, separate regular/Playoff/Toilet Bowl/other-postseason games, and milestones.', objectInput({ season: stringProp('Season year, for example 2025.'), leader_limit: numberProp('Maximum player leaders, 1-100.') }, ['season'])),
  tool('get_week_gamebook', 'Returns one historical East v. West weekly gamebook with every matchup, scores, team and player leaders, and milestones.', objectInput({ season: stringProp('Season year.'), week: numberProp('Fantasy week number.') }, ['season', 'week'])),
  tool('get_league_awards', 'Returns MVP, Rookie of the Year, All-EVW and scoring highs. Completed-season MVP/ROY winners are also persisted as immutable first-class award records.', objectInput({ season: stringProp('Optional season filter.'), limit: numberProp('Maximum scoring-high rows per category, 1-100.') })),
  tool('get_league_milestones', 'Returns the League Milestones archive: player EVW-point thresholds, franchise win milestones, record milestones, and championships. Supports team, player, season and milestone-type filters.', objectInput({ team: stringProp('Optional franchise name or alias.'), player: stringProp('Optional player-name filter.'), season: stringProp('Optional season.'), type: enumProp('Optional milestone type.', ['player', 'franchise', 'record', 'championship']), limit: numberProp('Maximum results, 1-100.') })),
  tool('get_hall_of_fame', 'Returns Team Hall of Fame inductees with induction class, biography, franchise-specific EVW production, starts and tenure. Supports franchise, player and induction-year filters.', objectInput({ team: stringProp('Optional franchise name or alias.'), player: stringProp('Optional player-name filter.'), induction_year: numberProp('Optional induction class year.'), limit: numberProp('Maximum results, 1-100.') })),
  tool('query_stats', 'East v. West Stats Explorer 2.0. Without group_by it behaves like the row-level explorer. With group_by it performs grouped analytics with count/sum/average/min/max/median, rank, and comparison to league average.', objectInput({
    entity: enumProp('Dataset to query.', ['player_career', 'player_season', 'player_games', 'games']),
    query: stringProp('Optional partial player name for player entities.'), position: enumProp('Optional player position.', PLAYER_POSITION_VALUES), franchise: stringProp('Optional franchise filter.'), season: stringProp('Exact season.'), season_from: stringProp('Earliest season.'), season_to: stringProp('Latest season.'), min_points: numberProp('Minimum points.'), max_points: numberProp('Maximum points.'), min_starts: numberProp('Minimum starts.'), min_weeks: numberProp('Minimum rostered weeks.'), min_ppg: numberProp('Minimum PPG.'), game_type: enumProp('Game category.', GAME_TYPE_VALUES), opponent: stringProp('Opponent filter for games.'), result: enumProp('Result filter for games.', ['W', 'L', 'T']), max_margin: numberProp('Maximum game margin.'), exclude_defenses: booleanProp('Exclude DEF/DST rows.'), sort: enumProp('Row sort field.', ['points', 'ppg', 'starts', 'weeks', 'best_game', 'best_season', 'franchises', 'score', 'margin', 'combined']), order: enumProp('Sort direction.', ['desc', 'asc']),
    group_by: enumProp('Optional grouped-analysis dimension.', ['franchise', 'season', 'position', 'player', 'game_type']), metric: enumProp('Metric to aggregate.', ['points', 'starts', 'weeks', 'ppg', 'margin', 'combined']), aggregate: enumProp('Primary group ranking value.', ['sum', 'average', 'count', 'min', 'max', 'median']), limit: numberProp('Maximum results/groups, 1-100.')
  }, ['entity'])),

  tool('resolve_entity', 'Canonical entity resolver for players, franchises and seasons. Returns confidence-ranked candidates and flags ambiguous matches instead of guessing.', objectInput({ query: stringProp('Name, alias, Sleeper player ID, or season.'), kind: enumProp('Entity kind.', ['auto', 'player', 'franchise', 'season']) }, ['query'])),
  tool('get_player_ownership_timeline', 'Returns a player ownership/tenure timeline across EVW franchises, with transitions, starts and production. Accepts player ID or name.', objectInput({ id: stringProp('Optional Sleeper player ID.'), player: stringProp('Optional player name.'), name: stringProp('Optional player name.') })),
  tool('get_roster_snapshot', 'Reconstructs a franchise roster and starting lineup for a historical season/week from the canonical weekly EVW scoring ledger.', objectInput({ season: stringProp('Season year.'), week: numberProp('Week.'), team: stringProp('Franchise name or alias.') }, ['season', 'week', 'team'])),
  tool('get_trade_tree', 'Returns recursive player or draft-pick asset lineage using the existing canonical East v. West trade-tree engine.', objectInput({ type: enumProp('Root asset type.', ['player', 'pick']), id: stringProp('Optional player ID.'), player: stringProp('Optional player name.'), name: stringProp('Optional player name.'), season: stringProp('Pick season.'), round: numberProp('Pick round.'), slot: numberProp('Draft slot.'), depth: numberProp('Tree depth, 1-8.') })),
  tool('get_transaction_intelligence', 'Ranks acquisitions by EVW production after acquisition and identifies costly drops using the complete waiver/free-agent/trade ledger.', objectInput({ season: stringProp('Optional season.'), team: stringProp('Optional franchise.'), type: enumProp('Transaction type.', ['all', 'waiver', 'free_agent', 'trade']), limit: numberProp('Maximum rows, 1-100.') })),
  tool('get_rivalry', 'Returns a complete franchise-vs-franchise history with regular, Playoff, Toilet Bowl and placement records, scoring extremes, season series and top rivalry players.', objectInput({ team1: stringProp('First franchise.'), team2: stringProp('Second franchise.'), include_games: booleanProp('Include every matchup row.'), limit: numberProp('Top rivalry players, 1-100.') }, ['team1', 'team2'])),
  tool('get_research_backend_status', 'Returns warehouse/storage status and validates the nine-part EVW research backend. Lazily freezes any missing completed-season snapshots, award records and completed record book.'),
] as const;
