export { TEAM_COMPARE_HTML, TEAM_COMPARE_RESOURCE } from './team-compare-html';
export { TEAM_COMPARE_WIDGET_URI, TEAM_COMPARE_OUTPUT_SCHEMA, TEAM_COMPARE_TOOL_META, TEAM_COMPARE_RESOURCE_META } from './team-compare-contract';
